Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-BuildSupportDir {
    $candidate = $null

    if ($env:BUILD_SUPPORT_DIR -and (Test-Path -LiteralPath $env:BUILD_SUPPORT_DIR -PathType Container)) {
        $candidate = $env:BUILD_SUPPORT_DIR
    }
    elseif (Test-Path -LiteralPath 'build_support' -PathType Container) {
        $candidate = 'build_support'
    }
    elseif ($env:TOOLS_DIR -and (Test-Path -LiteralPath $env:TOOLS_DIR -PathType Container)) {
        $candidate = $env:TOOLS_DIR
    }
    elseif (Test-Path -LiteralPath 'tools' -PathType Container) {
        $candidate = 'tools'
    }
    elseif (Test-Path -LiteralPath '../agenticdevharness/tools' -PathType Container) {
        $candidate = '../agenticdevharness/tools'
    }
    else {
        throw 'Error: ReadyOS build support directory not found. Set BUILD_SUPPORT_DIR to override.'
    }

    return (Resolve-Path -LiteralPath $candidate).Path
}

function Configure-ViceEnv {
    if (-not $IsMacOS) {
        return
    }

    $schemaDir = '/opt/homebrew/share/glib-2.0/schemas'
    if (-not $env:GSETTINGS_SCHEMA_DIR -and (Test-Path -LiteralPath (Join-Path $schemaDir 'gschemas.compiled'))) {
        $env:GSETTINGS_SCHEMA_DIR = $schemaDir
    }

    $shareDir = '/opt/homebrew/share'
    if (Test-Path -LiteralPath $shareDir -PathType Container) {
        if ($env:XDG_DATA_DIRS) {
            if (-not (":{0}:" -f $env:XDG_DATA_DIRS).Contains((":{0}:" -f $shareDir))) {
                $env:XDG_DATA_DIRS = '{0}:{1}' -f $shareDir, $env:XDG_DATA_DIRS
            }
        }
        else {
            $env:XDG_DATA_DIRS = $shareDir
        }
    }
}

function Resolve-CommandPath {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Candidates,

        [Parameter(Mandatory = $true)]
        [string]$ErrorMessage
    )

    foreach ($candidate in $Candidates) {
        $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($cmd) {
            return $cmd.Source
        }
    }

    throw $ErrorMessage
}

function Validate-ParseTraceDebug {
    param([string]$Value)
    if ($Value -notin @('0', '1')) {
        throw ("Error: --parse-trace-debug must be 0 or 1 (got '{0}')." -f $Value)
    }
}

function Current-ParseTraceDebug {
    if ($script:ParseTraceDebug) {
        return $script:ParseTraceDebug
    }
    if ($env:READYSHELL_PARSE_TRACE_DEBUG) {
        return $env:READYSHELL_PARSE_TRACE_DEBUG
    }
    return '0'
}

function Current-ParseTraceLabel {
    switch (Current-ParseTraceDebug) {
        '1' { return 'debug-trace (READYSHELL_OVERLAYSIZE=0x2480, __OVERLAYSTART__=0xA180)' }
        '0' { return 'release/default (READYSHELL_OVERLAYSIZE=0x2440, __OVERLAYSTART__=0xA1C0)' }
        default { return ('custom/unknown ({0})' -f (Current-ParseTraceDebug)) }
    }
}

function Update-DynamicVersion {
    $genDir = Join-Path $script:RepoRoot 'src/generated'
    New-Item -ItemType Directory -Force -Path $genDir | Out-Null

    $last = ''
    if (Test-Path -LiteralPath $script:VersionStateFile) {
        $state = Get-Content -LiteralPath $script:VersionStateFile -Raw
        $match = [regex]::Match($state, '[A-Z]')
        if ($match.Success) {
            $last = $match.Value
        }
    }

    if (-not $last) {
        $next = 'A'
    }
    elseif ($last -eq 'Z') {
        $next = 'A'
    }
    else {
        $next = [char](([int][char]$last) + 1)
    }

    $script:RunVersionSuffix = [string]$next
    $script:RunVersionText = '{0}{1}' -f $script:VersionBase, $script:RunVersionSuffix

    Set-Content -LiteralPath $script:VersionStateFile -Value $script:RunVersionSuffix -Encoding ascii

    $header = @(
        '/* Auto-generated by run.ps1. Do not edit by hand. */',
        '#ifndef READYOS_BUILD_VERSION_H',
        '#define READYOS_BUILD_VERSION_H',
        '',
        ('#define READYOS_VERSION_BASE "{0}"' -f $script:VersionBase),
        ('#define READYOS_VERSION_SUFFIX "{0}"' -f $script:RunVersionSuffix),
        ('#define READYOS_VERSION_TEXT "{0}"' -f $script:RunVersionText),
        ('#define READYOS_TITLE_TEXT "READY OS v{0}"' -f $script:RunVersionText),
        ('#define READYOS_BOOT_VERSION_TEXT "PRECOG V{0}"' -f $script:RunVersionText),
        '',
        '#endif /* READYOS_BUILD_VERSION_H */'
    )
    Set-Content -LiteralPath $script:VersionHeaderFile -Value $header -Encoding ascii

    $asm = @(
        '; Auto-generated by run.ps1. Do not edit by hand.',
        '',
        'msg_version:',
        ('    .byte "PRECOG V{0}"' -f $script:RunVersionText),
        'msg_version_end:'
    )
    Set-Content -LiteralPath $script:VersionAsmFile -Value $asm -Encoding ascii
}

function Show-Help {
    @'
Ready OS Run Script (PowerShell)

Usage: ./run.ps1 [flags] [option]

Modes (option):
  (none)         Run Ready OS normally (preboot.prg)
  test           Run REU test program standalone
  debug          Run with VICE monitor breakpoints at shim entry points
  warp           Run in warp mode (max speed for loading)
  launcher       Run launcher.prg directly (skip boot loader)
  editor         Run editor.prg directly (standalone, no REU switching)
  calcplus       Run calcplus.prg directly (standalone, no REU switching)
  hexview        Run hexview.prg directly (standalone, no REU switching)
  2048           Run game2048.prg directly (standalone, no REU switching)
  deminer        Run deminer.prg directly (standalone, no REU switching)
  cal26          Run cal26.prg directly (standalone, no REU switching)
  dizzy          Run dizzy.prg directly (standalone, no REU switching)
  readme         Run readme.prg directly (standalone, no REU switching)
  showcfg        Run BASIC APPS.CFG inspector (drive 8)
  monitor        Start with VICE monitor open immediately
  readyshell-mon Normal boot + remote monitor sockets/logging for readyshell debugging
  noreu          Run boot without REU (for testing error handling)
  help           Show this help

Flags:
  --skipbuild                  Skip automatic build before run
  --parse-trace-debug 0|1      Build ReadyShell in release(0) or debug-trace(1) profile
  --parse-trace-debug=0|1      Same as above (equals syntax)
  --interactive                Show a key-menu with common run combinations
  -h, --help                   Show this help
'@ | Write-Host
}

function Run-InteractiveMenu {
    @'
ReadyOS interactive launcher

  [1] Normal run (release profile build)
  [2] Normal run (debug-trace profile build)
  [3] Debug monitor mode (release profile build)
  [4] Debug monitor mode (debug-trace profile build)
  [5] Readyshell remote monitor (debug-trace profile build)
  [6] Normal run (skip build, keep current binaries)
  [q] Quit
'@ | Write-Host

    $choice = Read-Host 'Choice'
    switch ($choice) {
        '1' { $script:Mode = ''; $script:ParseTraceDebug = '0'; $script:SkipBuild = $false }
        '2' { $script:Mode = ''; $script:ParseTraceDebug = '1'; $script:SkipBuild = $false }
        '3' { $script:Mode = 'debug'; $script:ParseTraceDebug = '0'; $script:SkipBuild = $false }
        '4' { $script:Mode = 'debug'; $script:ParseTraceDebug = '1'; $script:SkipBuild = $false }
        '5' { $script:Mode = 'readyshell-mon'; $script:ParseTraceDebug = '1'; $script:SkipBuild = $false }
        '6' { $script:Mode = ''; $script:ParseTraceDebug = $null; $script:SkipBuild = $true }
        'q' { exit 0 }
        'Q' { exit 0 }
        default { throw ("Invalid selection: '{0}'" -f $choice) }
    }
}

function Assert-FileExists {
    param([string]$Path, [string]$Kind)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw ("Error: {0} not found: {1}" -f $Kind, $Path)
    }
}

function Check-Disk {
    param([string]$Path)
    Assert-FileExists -Path $Path -Kind 'Disk image'
}

function Check-Prg {
    param([string]$Path)
    Assert-FileExists -Path $Path -Kind 'Program file'
}

function Check-OSDisks {
    Check-Disk $script:DiskFile1
    Check-Disk $script:DiskFile2
}

function Ensure-Cal26RelSeeded {
    if (-not (Test-Path -LiteralPath $script:DiskFile1)) {
        return
    }

    $listing = & c1541 $script:DiskFile1 '-list' 2>$null | Out-String
    $eventsMatch = [regex]::Match($listing, '(?im)^\s*(\d+)\s+"cal26\.rel"\s+rel\b')
    $cfgMatch = [regex]::Match($listing, '(?im)^\s*(\d+)\s+"cal26cfg\.rel"\s+rel\b')

    $eventsBlocks = if ($eventsMatch.Success) { [int]$eventsMatch.Groups[1].Value } else { 0 }
    $cfgBlocks = if ($cfgMatch.Success) { [int]$cfgMatch.Groups[1].Value } else { 0 }

    if ($eventsBlocks -gt 0 -and $cfgBlocks -gt 0) {
        return
    }

    Write-Host ("Seeding/repairing CAL26 REL files on {0} ..." -f $script:DiskFile1)
    & python3 (Join-Path $script:BuildSupportDir 'seed_cal26_rel.py') '--disk' $script:DiskFile1 *> $null

    $listing = & c1541 $script:DiskFile1 '-list' 2>$null | Out-String
    $eventsMatch = [regex]::Match($listing, '(?im)^\s*(\d+)\s+"cal26\.rel"\s+rel\b')
    $cfgMatch = [regex]::Match($listing, '(?im)^\s*(\d+)\s+"cal26cfg\.rel"\s+rel\b')

    $eventsBlocks = if ($eventsMatch.Success) { [int]$eventsMatch.Groups[1].Value } else { 0 }
    $cfgBlocks = if ($cfgMatch.Success) { [int]$cfgMatch.Groups[1].Value } else { 0 }

    if ($eventsBlocks -le 0 -or $cfgBlocks -le 0) {
        throw 'Error: CAL26 data files not valid on disk after seeding.'
    }
}

function Print-Info {
    param(
        [string]$RunMode,
        [string]$Target
    )

    Write-Host '=== Ready OS ==='
    Write-Host ''
    Write-Host ("Mode: {0}" -f $RunMode)
    Write-Host ("VICE: {0}" -f $script:ViceName)
    Write-Host ("Target: {0}" -f $Target)
    Write-Host ("Disk8: {0}" -f $script:DiskFile1)
    Write-Host ("Disk9: {0}" -f $script:DiskFile2)
    Write-Host ("Build Support: {0}" -f $script:BuildSupportDir)
    Write-Host ("ReadyShell parse trace: {0}" -f (Current-ParseTraceLabel))
    Write-Host ''
}

function New-TempDir {
    param([string]$Prefix)
    $path = Join-Path ([System.IO.Path]::GetTempPath()) ("{0}{1}" -f $Prefix, [System.Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Force -Path $path | Out-Null
    return $path
}

function Get-ManifestCount {
    param([string]$ManifestPath)
    if (-not (Test-Path -LiteralPath $ManifestPath)) {
        return 0
    }
    return ((Get-Content -LiteralPath $ManifestPath | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Measure-Object).Count)
}

function Maybe-Build {
    Update-DynamicVersion
    Write-Host ("Build version: {0}" -f $script:RunVersionText)
    Write-Host ("ReadyShell parse trace profile: {0}" -f (Current-ParseTraceLabel))

    if ($script:ParseTraceDebug) {
        $env:READYSHELL_PARSE_TRACE_DEBUG = $script:ParseTraceDebug
    }
    elseif ($env:READYSHELL_PARSE_TRACE_DEBUG) {
        Validate-ParseTraceDebug $env:READYSHELL_PARSE_TRACE_DEBUG
    }

    if ($script:SkipBuild) {
        Write-Host 'Skipping build (--skipbuild): binaries keep their previous embedded version.'
        if ($script:ParseTraceDebug) {
            Write-Host 'Note: --parse-trace-debug affects build profile only. With --skipbuild, it does not rebuild binaries.'
        }
        Write-Host ''
        return
    }

    $preserveScript = Join-Path $script:BuildSupportDir 'preserve_d71_user_data.ps1'
    $preserveDir1 = $null
    $preservePrevDisk1 = $null
    $preserveDir2 = $null
    $preservePrevDisk2 = $null

    try {
        if (Test-Path -LiteralPath $script:DiskFile1) {
            $preserveDir1 = New-TempDir -Prefix 'readyos_preserve_d8.'
            $preservePrevDisk1 = Join-Path $preserveDir1 'previous.d71'
            Copy-Item -LiteralPath $script:DiskFile1 -Destination $preservePrevDisk1 -Force
            & pwsh -NoLogo -NoProfile -File $preserveScript backup $preservePrevDisk1 $preserveDir1
            $count = Get-ManifestCount -ManifestPath (Join-Path $preserveDir1 'manifest.tsv')
            if ($count -gt 0) {
                Write-Host ("Preserving {0} user file(s) from existing disk 8..." -f $count)
            }
        }

        if (Test-Path -LiteralPath $script:DiskFile2) {
            $preserveDir2 = New-TempDir -Prefix 'readyos_preserve_d9.'
            $preservePrevDisk2 = Join-Path $preserveDir2 'previous.d71'
            Copy-Item -LiteralPath $script:DiskFile2 -Destination $preservePrevDisk2 -Force
            & pwsh -NoLogo -NoProfile -File $preserveScript backup $preservePrevDisk2 $preserveDir2
            $count = Get-ManifestCount -ManifestPath (Join-Path $preserveDir2 'manifest.tsv')
            if ($count -gt 0) {
                Write-Host ("Preserving {0} user file(s) from existing disk 9..." -f $count)
            }
        }

        Write-Host 'Building fresh disk images (use --skipbuild to skip)...'
        & $script:MakeExe '-B' "READYOS_USE_PWSH=1" "BUILD_SUPPORT_DIR=$($script:BuildSupportDir)" $script:DiskFile1 $script:DiskFile2
        if ($LASTEXITCODE -ne 0) {
            throw 'Build failed during disk rebuild.'
        }

        Write-Host ''
    }
    catch {
        if ($preservePrevDisk1 -and (Test-Path -LiteralPath $preservePrevDisk1)) {
            Write-Host 'Restoring previous disk 8 image to keep user data...'
            Copy-Item -LiteralPath $preservePrevDisk1 -Destination $script:DiskFile1 -Force
        }
        if ($preservePrevDisk2 -and (Test-Path -LiteralPath $preservePrevDisk2)) {
            Write-Host 'Restoring previous disk 9 image to keep user data...'
            Copy-Item -LiteralPath $preservePrevDisk2 -Destination $script:DiskFile2 -Force
        }
        throw
    }
    finally {
        if ($preserveDir1) {
            Remove-Item -LiteralPath $preserveDir1 -Recurse -Force -ErrorAction SilentlyContinue
        }
        if ($preserveDir2) {
            Remove-Item -LiteralPath $preserveDir2 -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

function Start-ViceProcess {
    param(
        [string[]]$Arguments,
        [string]$RedirectPath = ''
    )

    if ($IsMacOS) {
        $quoteArg = {
            param([string]$Value)
            return "'" + ($Value -replace "'", "'""'""'") + "'"
        }

        $commandParts = @('exec', (& $quoteArg $script:ViceExe))
        foreach ($arg in $Arguments) {
            $commandParts += (& $quoteArg $arg)
        }
        if ($RedirectPath) {
            $commandParts += @('>', (& $quoteArg $RedirectPath), '2>&1')
        }

        $startArgs = @{
            FilePath = '/bin/sh'
            ArgumentList = @('-lc', ($commandParts -join ' '))
            PassThru = $true
        }
    }
    else {
        $startArgs = @{
            FilePath = $script:ViceExe
            ArgumentList = $Arguments
            PassThru = $true
        }

        if ($RedirectPath) {
            $startArgs.RedirectStandardOutput = $RedirectPath
            $startArgs.RedirectStandardError = $RedirectPath
        }
    }

    $process = Start-Process @startArgs
    Start-Sleep -Seconds 1

    if ($process.HasExited) {
        throw ("VICE exited immediately with code {0}" -f $process.ExitCode)
    }

    Write-Host ("VICE launched (pid {0})." -f $process.Id)
    return $process
}

$script:RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $script:RepoRoot

$script:BuildSupportDir = Resolve-BuildSupportDir
Configure-ViceEnv

$script:DiskFile1 = 'readyos.d71'
$script:DiskFile2 = 'readyos_2.d71'
$script:PrebootPrg = 'preboot.prg'
$script:TestPrg = 'test_reu.prg'
$script:LauncherPrg = 'launcher.prg'
$script:EditorPrg = 'editor.prg'
$script:CalcplusPrg = 'calcplus.prg'
$script:HexviewPrg = 'hexview.prg'
$script:Game2048Prg = 'game2048.prg'
$script:DeminerPrg = 'deminer.prg'
$script:Cal26Prg = 'cal26.prg'
$script:DizzyPrg = 'dizzy.prg'
$script:ReadmePrg = 'readme.prg'
$script:ShowcfgPrg = 'showcfg.prg'

$script:VersionBase = '0.1.6'
$script:VersionStateFile = Join-Path ([System.IO.Path]::GetTempPath()) 'readyos_run_version_suffix.txt'
$script:VersionHeaderFile = Join-Path $script:RepoRoot 'src/generated/build_version.h'
$script:VersionAsmFile = Join-Path $script:RepoRoot 'src/generated/msg_version.inc'
$script:RemoteMonAddr = '127.0.0.1:6510'
$script:BinaryMonAddr = '127.0.0.1:6502'
$script:RemoteMonLog = 'logs/vice_remote_monitor.log'
$script:ViceStdioLog = 'logs/vice_readyshell_mon.out'
$script:ViceLogFile = 'logs/vice.log'

$script:ViceExe = Resolve-CommandPath -Candidates @('x64sc', 'x64') -ErrorMessage 'Error: VICE emulator not found (tried x64sc, x64)'
$script:ViceName = Split-Path -Leaf $script:ViceExe
$script:MakeExe = Resolve-CommandPath -Candidates @('make', 'gmake') -ErrorMessage 'Error: make/gmake not found in PATH'

$script:ViceOpts = @(
    '-logfile', $script:ViceLogFile,
    '-reu',
    '-reusize', '16384',
    '-drive8type', '1571',
    '-drive8truedrive',
    '-devicebackend8', '0',
    '+busdevice8',
    '-drive9type', '1571',
    '-drive9truedrive',
    '-devicebackend9', '0',
    '+busdevice9'
)

$script:SkipBuild = $false
$script:Mode = ''
$script:ParseTraceDebug = $null
$interactive = $false

for ($i = 0; $i -lt $args.Count; ) {
    $arg = $args[$i]
    switch -Regex ($arg) {
        '^-h$|^--help$' {
            Show-Help
            exit 0
        }
        '^--skipbuild$' {
            $script:SkipBuild = $true
            $i += 1
        }
        '^--interactive$' {
            $interactive = $true
            $i += 1
        }
        '^--parse-trace-debug$' {
            if ($i + 1 -ge $args.Count) {
                throw 'Error: --parse-trace-debug requires value 0 or 1.'
            }
            $script:ParseTraceDebug = $args[$i + 1]
            Validate-ParseTraceDebug $script:ParseTraceDebug
            $i += 2
        }
        '^--parse-trace-debug=(.+)$' {
            $script:ParseTraceDebug = $Matches[1]
            Validate-ParseTraceDebug $script:ParseTraceDebug
            $i += 1
        }
        default {
            if ($script:Mode) {
                throw ("Unknown option: {0}" -f $arg)
            }
            $script:Mode = $arg
            $i += 1
        }
    }
}

if ($script:ParseTraceDebug) {
    $env:READYSHELL_PARSE_TRACE_DEBUG = $script:ParseTraceDebug
}
elseif ($env:READYSHELL_PARSE_TRACE_DEBUG) {
    Validate-ParseTraceDebug $env:READYSHELL_PARSE_TRACE_DEBUG
}

if ($interactive) {
    if ($script:Mode) {
        throw ("Error: --interactive cannot be combined with an explicit mode ('{0}')." -f $script:Mode)
    }
    Run-InteractiveMenu
}

switch ($script:Mode) {
    { $_ -in @('help', '-h', '--help') } {
        Show-Help
        exit 0
    }

    'test' {
        Maybe-Build
        Check-Prg $script:TestPrg
        Print-Info -RunMode 'REU Test' -Target $script:TestPrg
        Write-Host 'Running standalone REU test program...'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:TestPrg)) | Out-Null
    }

    'debug' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        Print-Info -RunMode 'Debug' -Target $script:PrebootPrg
        Write-Host 'Debug mode - VICE monitor available (Alt+M)'
        Write-Host ''
        $debugFile = Join-Path ([System.IO.Path]::GetTempPath()) ("vice_debug_{0}.cmd" -f [System.Guid]::NewGuid().ToString('N'))
        try {
            Set-Content -LiteralPath $debugFile -Value @('break C809', 'break C80c', 'break C80f') -Encoding ascii
            Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-9', $script:DiskFile2, '-moncommands', $debugFile, '-autostart', $script:PrebootPrg)) | Out-Null
        }
        finally {
            Remove-Item -LiteralPath $debugFile -Force -ErrorAction SilentlyContinue
        }
    }

    'warp' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        Print-Info -RunMode 'Warp Mode' -Target $script:PrebootPrg
        Write-Host 'Warp mode enabled - max speed loading'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-warp', '-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostart', $script:PrebootPrg)) | Out-Null
    }

    'launcher' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:LauncherPrg
        Print-Info -RunMode 'Direct Launch' -Target $script:LauncherPrg
        Write-Host 'Running launcher directly (skipping boot loader)'
        Write-Host 'Note: Shim will NOT be installed - REU switching will not work.'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostartprgmode', '1', $script:LauncherPrg)) | Out-Null
    }

    'editor' {
        Maybe-Build
        Check-Prg $script:EditorPrg
        Print-Info -RunMode 'Standalone' -Target $script:EditorPrg
        Write-Host 'Running editor standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:EditorPrg)) | Out-Null
    }

    'calcplus' {
        Maybe-Build
        Check-Prg $script:CalcplusPrg
        Print-Info -RunMode 'Standalone' -Target $script:CalcplusPrg
        Write-Host 'Running calculator plus standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:CalcplusPrg)) | Out-Null
    }

    'hexview' {
        Maybe-Build
        Check-Prg $script:HexviewPrg
        Print-Info -RunMode 'Standalone' -Target $script:HexviewPrg
        Write-Host 'Running hex viewer standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:HexviewPrg)) | Out-Null
    }

    '2048' {
        Maybe-Build
        Check-Prg $script:Game2048Prg
        Print-Info -RunMode 'Standalone' -Target $script:Game2048Prg
        Write-Host 'Running 2048 standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:Game2048Prg)) | Out-Null
    }

    'deminer' {
        Maybe-Build
        Check-Prg $script:DeminerPrg
        Print-Info -RunMode 'Standalone' -Target $script:DeminerPrg
        Write-Host 'Running Deminer standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:DeminerPrg)) | Out-Null
    }

    'cal26' {
        Maybe-Build
        Check-Disk $script:DiskFile1
        Ensure-Cal26RelSeeded
        Check-Prg $script:Cal26Prg
        Print-Info -RunMode 'Standalone' -Target $script:Cal26Prg
        Write-Host 'Running CAL26 standalone (no REU, no shim, disk attached)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-autostartprgmode', '1', $script:Cal26Prg)) | Out-Null
    }

    'dizzy' {
        Maybe-Build
        Check-Disk $script:DiskFile1
        Check-Prg $script:DizzyPrg
        Print-Info -RunMode 'Standalone' -Target $script:DizzyPrg
        Write-Host 'Running DIZZY standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-autostartprgmode', '1', $script:DizzyPrg)) | Out-Null
    }

    'readme' {
        Maybe-Build
        Check-Prg $script:ReadmePrg
        Print-Info -RunMode 'Standalone' -Target $script:ReadmePrg
        Write-Host 'Running README app standalone (no REU, no shim)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-autostartprgmode', '1', $script:ReadmePrg)) | Out-Null
    }

    'showcfg' {
        Maybe-Build
        Check-Disk $script:DiskFile1
        Check-Prg $script:ShowcfgPrg
        Print-Info -RunMode 'Catalog Inspector' -Target $script:ShowcfgPrg
        Write-Host 'Running BASIC APPS.CFG inspector (reads apps.cfg from drive 8)'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostartprgmode', '1', $script:ShowcfgPrg)) | Out-Null
    }

    'monitor' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        Print-Info -RunMode 'Monitor' -Target $script:PrebootPrg
        Write-Host 'Starting with monitor open...'
        Write-Host ''
        Start-ViceProcess ($script:ViceOpts + @('-initbreak', '0xC80D', '-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostart', $script:PrebootPrg)) | Out-Null
    }

    'readyshell-mon' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        New-Item -ItemType Directory -Force -Path 'logs' | Out-Null
        Set-Content -LiteralPath $script:RemoteMonLog -Value $null -Encoding ascii
        Set-Content -LiteralPath $script:ViceStdioLog -Value $null -Encoding ascii
        Print-Info -RunMode 'Readyshell Remote Monitor' -Target $script:PrebootPrg
        Write-Host ("Starting ReadyOS with remote monitor endpoints enabled:")
        Write-Host ("  text monitor:   {0}" -f $script:RemoteMonAddr)
        Write-Host ("  binary monitor: {0}" -f $script:BinaryMonAddr)
        Write-Host ("  text log:       {0}" -f $script:RemoteMonLog)
        Write-Host ("  VICE stdio log: {0}" -f $script:ViceStdioLog)
        Write-Host ''
        Start-ViceProcess -Arguments ($script:ViceOpts + @(
            '-remotemonitor',
            '-remotemonitoraddress', $script:RemoteMonAddr,
            '-binarymonitor',
            '-binarymonitoraddress', $script:BinaryMonAddr,
            '-monlog',
            '-monlogname', $script:RemoteMonLog,
            '-8', $script:DiskFile1,
            '-9', $script:DiskFile2,
            '-autostart', $script:PrebootPrg
        )) -RedirectPath $script:ViceStdioLog | Out-Null
    }

    'noreu' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        Print-Info -RunMode 'No REU' -Target $script:PrebootPrg
        Write-Host 'Running WITHOUT REU (testing error handling)'
        Write-Host ''
        Start-ViceProcess (@('-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostart', $script:PrebootPrg)) | Out-Null
    }

    '' {
        Maybe-Build
        Check-OSDisks
        Ensure-Cal26RelSeeded
        Check-Prg $script:PrebootPrg
        Print-Info -RunMode 'Normal' -Target $script:PrebootPrg
        @(
            'Instructions:',
            '  1. preboot.prg loads/runs setd71.prg; setd71 sets drives 8/9 to 1571 mode, then loads boot.prg',
            '  2. Boot loader installs shim and loads launcher',
            '  3. Select ''LOAD TO REU'' and press RETURN to preload apps',
            '  4. Select an app (including 2048 and deminer) and press RETURN to launch',
            '  5. Press CTRL+B to return to launcher',
            '  6. Press F2/F4 to switch between apps',
            ''
        ) | Write-Host
        Start-ViceProcess ($script:ViceOpts + @('-8', $script:DiskFile1, '-9', $script:DiskFile2, '-autostart', $script:PrebootPrg)) | Out-Null
    }

    default {
        throw ("Unknown option: {0}" -f $script:Mode)
    }
}
