#!/usr/bin/env python3
"""
Update ReadyOS build version assets.

This is the shared version entrypoint for Makefile, run.sh, and run.ps1.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GEN_DIR = ROOT / "src" / "generated"
HEADER_PATH = GEN_DIR / "build_version.h"
ASM_PATH = GEN_DIR / "msg_version.inc"
STATE_PATH = Path("/tmp/readyos_run_version_suffix.txt")
BASE_VERSION = "0.1.8"


def read_current_version() -> str:
    if not HEADER_PATH.exists():
        return f"{BASE_VERSION}A"
    text = HEADER_PATH.read_text(encoding="utf-8", errors="strict")
    match = re.search(r'#define\s+READYOS_VERSION_TEXT\s+"([^"]+)"', text)
    if not match:
        return f"{BASE_VERSION}A"
    return match.group(1)


def read_last_suffix() -> str:
    if not STATE_PATH.exists():
        current = read_current_version()
        if current.startswith(BASE_VERSION) and len(current) == len(BASE_VERSION) + 1:
            suffix = current[-1]
            if "A" <= suffix <= "Z":
                return suffix
        return ""
    raw = STATE_PATH.read_text(encoding="ascii", errors="ignore")
    match = re.search(r"[A-Z]", raw)
    return match.group(0) if match else ""


def next_version_text() -> str:
    suffix = read_last_suffix()
    if not suffix:
        next_suffix = "A"
    elif suffix == "Z":
        next_suffix = "A"
    else:
        next_suffix = chr(ord(suffix) + 1)
    return f"{BASE_VERSION}{next_suffix}"


def split_version_text(version_text: str) -> tuple[str, str]:
    if not version_text.startswith(BASE_VERSION):
        raise ValueError(f"version must start with {BASE_VERSION}: {version_text}")

    suffix = version_text[len(BASE_VERSION):]
    if suffix == "":
        return version_text, suffix
    if len(suffix) == 1 and "A" <= suffix <= "Z":
        return version_text, suffix
    raise ValueError(f"version suffix must be empty or A..Z: {version_text}")


def write_version(version_text: str) -> None:
    version_text, suffix = split_version_text(version_text)

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(
        "\n".join(
            [
                "/* Auto-generated by update_build_version.py. Do not edit by hand. */",
                "#ifndef READYOS_BUILD_VERSION_H",
                "#define READYOS_BUILD_VERSION_H",
                "",
                f'#define READYOS_VERSION_BASE "{BASE_VERSION}"',
                f'#define READYOS_VERSION_SUFFIX "{suffix}"',
                f'#define READYOS_VERSION_TEXT "{version_text}"',
                f'#define READYOS_TITLE_TEXT "READY OS v{version_text}"',
                f'#define READYOS_BOOT_VERSION_TEXT "v{version_text}"',
                "",
                "#endif /* READYOS_BUILD_VERSION_H */",
                "",
            ]
        ),
        encoding="ascii",
    )
    ASM_PATH.write_text(
        "\n".join(
            [
                "; Auto-generated by update_build_version.py. Do not edit by hand.",
                "",
                "msg_version:",
                f'    .byte "v{version_text}"',
                "msg_version_end:",
                "",
            ]
        ),
        encoding="ascii",
    )
    if suffix:
        STATE_PATH.write_text(f"{suffix}\n", encoding="ascii")


def main() -> int:
    ap = argparse.ArgumentParser()
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--next", action="store_true",
                       help="Advance the rolling suffix and write the version assets.")
    group.add_argument("--write", metavar="VERSION",
                       help="Write the supplied version text to the generated assets.")
    group.add_argument("--current", action="store_true",
                       help="Print the current version text without mutating anything.")
    args = ap.parse_args()

    if args.current:
        print(read_current_version())
        return 0

    try:
        version_text = args.write if args.write else next_version_text()
        write_version(version_text)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(version_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
